import type { MessageOutboxCopy } from '@/components/settings/message-outbox-section';
import type { AppLocale } from '@/i18n/catalog';

const copy: Record<AppLocale, MessageOutboxCopy> = {
  en: {
    title: 'Messages waiting to send',
    description: 'Unsent messages stay encrypted on this device and are scoped to this account and company.',
    emptyTitle: 'Everything is sent',
    emptyBody: 'There are no unsent message bodies stored in the local queue.',
    queued: 'Queued',
    sending: 'Sending',
    failed: 'Failed',
    attempts: 'Attempts:',
    created: 'Queued:',
    unknownConversation: 'Conversation no longer available',
    edit: 'Edit',
    retry: 'Retry',
    cancel: 'Cancel',
    editTitle: 'Edit queued message',
    editDescription: 'Editing is available only before the first delivery attempt. The same message identity is preserved.',
    message: 'Message',
    save: 'Save and send',
    cancelTitle: 'Cancel queued message?',
    cancelDescription: 'This removes the unsent local copy from this device.',
    cancelAmbiguousDescription: 'A previous delivery attempt may already have reached the service. Cancelling removes only this local queue item.',
    cancelConfirm: 'Cancel message',
    ambiguous: 'Delivery is uncertain. After reconnecting, Newone may restore a server-accepted message during authoritative reconciliation.',
    errorCode: 'Failure code',
    queueUnavailable: 'Local message queue unavailable on this device; messages are sent directly instead. Reason:',
  },
  ko: {
    title: '전송 대기 중인 메시지',
    description: '전송되지 않은 메시지는 이 계정과 회사에 연결된 상태로 이 기기에서 암호화되어 보관됩니다.',
    emptyTitle: '모두 전송되었습니다',
    emptyBody: '로컬 대기열에 저장된 미전송 메시지 본문이 없습니다.',
    queued: '대기 중',
    sending: '전송 중',
    failed: '실패',
    attempts: '시도 횟수:',
    created: '대기 시작:',
    unknownConversation: '더 이상 이용할 수 없는 대화',
    edit: '수정',
    retry: '다시 시도',
    cancel: '취소',
    editTitle: '대기 중인 메시지 수정',
    editDescription: '첫 전송 시도 전까지만 수정할 수 있습니다. 동일한 메시지 식별자는 유지됩니다.',
    message: '메시지',
    save: '저장 후 전송',
    cancelTitle: '대기 중인 메시지를 취소할까요?',
    cancelDescription: '이 기기에서 전송되지 않은 로컬 사본을 제거합니다.',
    cancelAmbiguousDescription: '이전 전송 시도가 이미 서비스에 도달했을 수 있습니다. 취소하면 이 로컬 대기열 항목만 제거됩니다.',
    cancelConfirm: '메시지 취소',
    ambiguous: '전송 여부가 불확실합니다. 다시 연결되면 서버에서 수락된 메시지가 권한 기반 동기화 중 복원될 수 있습니다.',
    errorCode: '오류 코드',
    queueUnavailable: '이 기기에서 로컬 메시지 대기열을 사용할 수 없어 메시지를 바로 전송합니다. 원인:',
  },
  es: {
    title: 'Mensajes pendientes de envío',
    description: 'Los mensajes no enviados permanecen cifrados en este dispositivo y vinculados a esta cuenta y empresa.',
    emptyTitle: 'Todo está enviado',
    emptyBody: 'No hay cuerpos de mensajes sin enviar guardados en la cola local.',
    queued: 'En cola',
    sending: 'Enviando',
    failed: 'Fallido',
    attempts: 'Intentos:',
    created: 'En cola desde:',
    unknownConversation: 'Conversación ya no disponible',
    edit: 'Editar',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    editTitle: 'Editar mensaje en cola',
    editDescription: 'Solo se puede editar antes del primer intento de entrega. Se conserva la misma identidad del mensaje.',
    message: 'Mensaje',
    save: 'Guardar y enviar',
    cancelTitle: '¿Cancelar el mensaje en cola?',
    cancelDescription: 'Esto elimina de este dispositivo la copia local que no se ha enviado.',
    cancelAmbiguousDescription: 'Un intento anterior podría haber llegado al servicio. Cancelar solo elimina este elemento de la cola local.',
    cancelConfirm: 'Cancelar mensaje',
    ambiguous: 'La entrega es incierta. Al volver a conectarse, Newone puede restaurar un mensaje aceptado por el servidor durante la conciliación autorizada.',
    errorCode: 'Código de fallo',
    queueUnavailable: 'La cola local de mensajes no está disponible en este dispositivo; los mensajes se envían directamente. Motivo:',
  },
};

export function outboxCopy(locale: AppLocale) {
  return copy[locale];
}
