const COPY = {
  en: {
    button: 'Mention people',
    close: 'Close mentions',
    title: 'Notify specific people',
    description: 'Choose who to notify.',
    searchLabel: 'Search people to mention',
    searchPlaceholder: 'Search people',
    selected: 'Selected',
    available: 'People',
    limit: 'Up to 50 people per message',
    noMatches: 'No one matches.',
    remove: 'Remove mention',
    mentioned: 'Mentioned',
    you: 'you',
    member: 'member',
    invalid: 'You can mention up to 50 people in this chat.',
  },
  ko: {
    button: '사람 멘션',
    close: '멘션 닫기',
    title: '특정 사람에게 알림',
    description: '알릴 사람을 선택하세요.',
    searchLabel: '멘션할 사람 검색',
    searchPlaceholder: '사람 검색',
    selected: '선택됨',
    available: '참여자',
    limit: '메시지당 최대 50명',
    noMatches: '일치하는 사람이 없습니다.',
    remove: '멘션 삭제',
    mentioned: '멘션됨',
    you: '나',
    member: '멤버',
    invalid: '이 채팅에서는 최대 50명까지 멘션할 수 있습니다.',
  },
  es: {
    button: 'Mencionar personas',
    close: 'Cerrar menciones',
    title: 'Avisar a personas específicas',
    description: 'Elige a quién avisar.',
    searchLabel: 'Buscar personas para mencionar',
    searchPlaceholder: 'Buscar personas',
    selected: 'Seleccionadas',
    available: 'Personas',
    limit: 'Hasta 50 personas por mensaje',
    noMatches: 'Nadie coincide.',
    remove: 'Quitar mención',
    mentioned: 'Mencionó a',
    you: 'ti',
    member: 'miembro',
    invalid: 'Puedes mencionar hasta 50 personas en este chat.',
  },
} as const;

export function mentionCopy(locale: string) {
  return COPY[locale === 'ko' || locale === 'es' ? locale : 'en'];
}
