const COPY = {
  en: {
    button: 'Mention people',
    close: 'Close mentions',
    title: 'Notify specific people',
    description: 'Select current conversation members. Mentions can notify them when their setting is Mentions only.',
    searchLabel: 'Search conversation members to mention',
    searchPlaceholder: 'Search members',
    selected: 'Selected',
    available: 'Available members',
    limit: 'Up to 50 people per message',
    noMatches: 'No matching conversation members.',
    remove: 'Remove mention',
    mentioned: 'Mentioned',
    you: 'you',
    member: 'member',
    invalid: 'Mentions must be unique, current conversation members, and no more than 50 people.',
  },
  ko: {
    button: '사람 멘션',
    close: '멘션 닫기',
    title: '특정 사람에게 알림',
    description: '현재 대화 멤버를 선택하세요. 멘션 알림만 받는 사람에게도 알림이 갈 수 있습니다.',
    searchLabel: '멘션할 대화 멤버 검색',
    searchPlaceholder: '멤버 검색',
    selected: '선택됨',
    available: '선택 가능한 멤버',
    limit: '메시지당 최대 50명',
    noMatches: '일치하는 대화 멤버가 없습니다.',
    remove: '멘션 삭제',
    mentioned: '멘션됨',
    you: '나',
    member: '멤버',
    invalid: '멘션은 현재 대화 멤버여야 하며 중복 없이 최대 50명까지 선택할 수 있습니다.',
  },
  es: {
    button: 'Mencionar personas',
    close: 'Cerrar menciones',
    title: 'Avisar a personas específicas',
    description: 'Selecciona miembros actuales de la conversación. Una mención puede avisarles si usan Solo menciones.',
    searchLabel: 'Buscar miembros de la conversación para mencionar',
    searchPlaceholder: 'Buscar miembros',
    selected: 'Seleccionadas',
    available: 'Miembros disponibles',
    limit: 'Hasta 50 personas por mensaje',
    noMatches: 'No hay miembros de la conversación que coincidan.',
    remove: 'Quitar mención',
    mentioned: 'Mencionó a',
    you: 'ti',
    member: 'miembro',
    invalid: 'Las menciones deben ser miembros actuales, sin duplicados y con un máximo de 50 personas.',
  },
} as const;

export function mentionCopy(locale: string) {
  return COPY[locale === 'ko' || locale === 'es' ? locale : 'en'];
}
