import type { AppLocale } from '@/i18n/catalog';

const en = {
  previewAudience: 'Preview audience',
  previewRequired: 'Preview the current audience before publishing.',
  previewLoading: 'Checking current recipients…',
  audienceSnapshot: 'Audience snapshot',
  recipients: 'active recipients',
  excluded: 'excluded inactive members',
  languages: 'Notification languages',
  previewBasis: 'This preview is dynamic. The immutable recipient snapshot is created only when the update is actually published.',
  audienceBuilder: 'Target audience',
  audienceBuilderDescription: 'Choose one base scope, then optionally narrow it by operational role, access tier, preferred language, or who is currently on shift.',
  companyAudience: 'Entire company',
  channelAudience: 'Announcement channel members',
  unitAudience: 'Sites and units',
  sites: 'Sites',
  departments: 'Departments',
  teams: 'Teams',
  lines: 'Lines',
  units: 'Shifts and other units',
  descendantDisclosure: 'Selecting a site or department includes people assigned only to its descendant departments, teams, lines, and shifts.',
  unitRequired: 'Select at least one site, department, team, line, or unit.',
  operationalRoles: 'Operational roles',
  operationalRolesDescription: 'Exact job titles and configured workplace roles. These are not account access tiers.',
  configuredRoles: 'Configured roles (comma-separated)',
  configuredRolesPlaceholder: 'forklift_operator, safety_coordinator',
  configuredRolesInvalid: 'Use no more than 50 exact role values, each 160 characters or fewer.',
  accessRoles: 'Account access tiers',
  accessRolesDescription: 'Optional security-tier filter, kept separate from job and operational roles.',
  owner: 'Owner',
  admin: 'Admin',
  manager: 'Manager',
  member: 'Member',
  preferredLanguages: 'Preferred message languages',
  currentShiftOnly: 'Currently on shift only',
  currentShiftDescription: 'Requires an authoritative company schedule. Scheduled updates are reevaluated at their actual publication time.',
  exclusionBreakdown: 'Excluded',
  inactive: 'inactive',
  selectorMismatch: 'outside selectors',
  scheduledFor: 'Scheduled publication',
  schedulePlaceholder: 'ISO date/time, for example 2030-08-10T10:00:00Z',
  publishNow: 'Publish now',
  in15Minutes: 'In 15 min',
  inOneHour: 'In 1 hour',
  tomorrow: 'Tomorrow',
  scheduleInvalid: 'Use a future ISO date and time.',
  notificationClass: 'Notification class',
  routine: 'Routine',
  urgent: 'Urgent',
  critical: 'Critical',
  notificationMapping: 'The server maps Normal → Routine, Important → Urgent, and Emergency → Critical. Clients cannot override that mapping.',
  overrideCategory: 'Authorized override category',
  safety: 'Safety',
  security: 'Security',
  operations: 'Operations',
  weather: 'Weather',
  businessContinuity: 'Business continuity',
  overrideReason: 'Quiet-hours override reason',
  overrideReasonPlaceholder: 'Why off-shift or muted delivery is operationally authorized',
  overrideAudit: 'Urgent and critical delivery requires recent MFA, an approved category, and an audited reason. It does not replace emergency alarms or emergency services.',
  attestation: 'Require an attestation',
  attestationPrompt: 'Attestation prompt',
  attestationPlaceholder: 'I have read and understood these instructions.',
  attestationEvidence: 'Newone records the exact notice version plus an attributable session/installation snapshot. It never treats opening or scrolling as acknowledgement.',
  reminders: 'Enable acknowledgement reminders',
  deadline: 'Acknowledgement deadline',
  deadlinePlaceholder: 'Future ISO date/time',
  intervalMinutes: 'Reminder interval (minutes)',
  maximumReminders: 'Maximum reminders (1–20)',
  escalateMinutes: 'Escalate after publication (minutes)',
  policyInvalid: 'Deadline, reminder interval, and escalation must satisfy the displayed bounds.',
  smsDisabled: 'SMS fallback is disabled in this build. Configure and approve an external fallback before claiming SMS delivery.',
  publisherView: 'Publisher control center',
  publisherDescription: 'Scheduled items, immutable correction history, and notice-scoped response state. Requires recent MFA.',
  refreshPublisher: 'Refresh publisher view',
  recentMfaRequired: 'Verify with MFA again to load publisher response details.',
  noManagedUpdates: 'No updates are available in your authorized publisher scope.',
  snapshotPending: 'Audience snapshot pending until publication',
  statusDraft: 'Draft',
  statusScheduled: 'Scheduled',
  statusPublished: 'Published',
  statusCancelled: 'Cancelled',
  statusArchived: 'Archived',
  acknowledgementRequired: 'Acknowledgement required',
  noAcknowledgementRequired: 'No acknowledgement required',
  noNonResponders: 'Everyone in the snapshotted audience has acknowledged this version.',
  notRead: 'Not read',
  immutableHistory: 'Prior versions remain immutable and auditable.',
  version: 'Version',
  versions: 'Version history',
  delivered: 'Delivered',
  read: 'Read',
  acknowledgedCount: 'Acknowledged',
  overdue: 'Overdue',
  unreachable: 'No active push device',
  nonAcknowledged: 'Not acknowledged',
  viewNonResponders: 'View non-acknowledgers',
  nonResponderTitle: 'Notice-scoped non-acknowledgers',
  nonResponderPrivacy: 'This authorized list contains only response state for this exact notice version. It does not expose unrelated chats or activity.',
  loadMore: 'Load more',
  pendingReachability: 'Push pending',
  deliveredReachability: 'Delivered',
  unreachableReachability: 'No active push device',
  reminded: 'Reminders',
  escalated: 'Escalated',
  cancelScheduled: 'Cancel scheduled update',
  cancelReason: 'Cancellation reason',
  cancelReasonPlaceholder: 'Why this scheduled publication must not be sent',
  confirmCancel: 'Cancel publication',
  correct: 'Publish correction',
  correctionTitle: 'Correct published update',
  correctionDescription: 'A correction creates a new immutable version. Prior versions and acknowledgements remain recorded; recipients must acknowledge the new version when required.',
  correctionReason: 'Correction reason',
  correctionReasonPlaceholder: 'What changed and why',
  publishCorrection: 'Publish corrected version',
  correctedFrom: 'Corrects',
  openUpdate: 'Open update',
  detailTitle: 'Official update',
  markReadBoundary: 'Opening this detail records read state only. It does not acknowledge understanding.',
  acknowledgeTitle: 'Acknowledge exact version',
  acknowledgeDescription: 'This deliberate action binds your acknowledgement to the displayed immutable version.',
  confirmAttestation: 'I confirm the required statement',
  confirmAcknowledgement: 'Acknowledge this version',
  acknowledgementRecorded: 'Acknowledgement recorded with attributable session evidence.',
  close: 'Close',
  serverRejected: 'The secure update service rejected this action. Refresh the authoritative state before retrying.',
  networkError: 'Newone could not reach the secure update service. No completion is assumed.',
  saved: 'Authoritative update state refreshed.',
} as const;

type UpdateCopy = { [Key in keyof typeof en]: string };

const ko: UpdateCopy = {
  audienceBuilder: '대상 수신자',
  audienceBuilderDescription: '기본 범위를 하나 선택한 뒤 운영 역할, 접근 등급, 선호 언어 또는 현재 근무 중인 사람으로 선택적으로 좁힙니다.',
  companyAudience: '회사 전체',
  channelAudience: '공지 채널 구성원',
  unitAudience: '사업장 및 조직 단위',
  sites: '사업장',
  departments: '부서',
  teams: '팀',
  lines: '라인',
  units: '교대 및 기타 조직 단위',
  descendantDisclosure: '사업장이나 부서를 선택하면 하위 부서, 팀, 라인, 교대에만 배정된 사람도 포함됩니다.',
  unitRequired: '사업장, 부서, 팀, 라인 또는 조직 단위를 하나 이상 선택하세요.',
  operationalRoles: '운영 역할',
  operationalRolesDescription: '정확한 직책 및 구성된 업무 역할입니다. 계정 접근 등급이 아닙니다.',
  configuredRoles: '구성된 역할(쉼표로 구분)',
  configuredRolesPlaceholder: 'forklift_operator, safety_coordinator',
  configuredRolesInvalid: '정확한 역할 값을 최대 50개, 각각 160자 이하로 입력하세요.',
  accessRoles: '계정 접근 등급',
  accessRolesDescription: '직책 및 운영 역할과 분리된 선택적 보안 등급 필터입니다.',
  owner: '소유자', admin: '관리자', manager: '매니저', member: '구성원',
  preferredLanguages: '선호 메시지 언어',
  currentShiftOnly: '현재 근무 중인 사람만',
  currentShiftDescription: '권한 있는 회사 일정이 필요합니다. 예약 공지는 실제 게시 시점에 다시 평가됩니다.',
  exclusionBreakdown: '제외', inactive: '비활성', selectorMismatch: '선택 조건 외',
  statusDraft: '초안',
  statusScheduled: '예약됨',
  statusPublished: '게시됨',
  statusCancelled: '취소됨',
  statusArchived: '보관됨',
  acknowledgementRequired: '확인 필요',
  noAcknowledgementRequired: '확인 불필요',
  noNonResponders: '스냅샷에 포함된 모든 수신자가 이 버전을 확인했습니다.',
  notRead: '읽지 않음',
  immutableHistory: '이전 버전은 변경 불가능하며 감사 가능하게 유지됩니다.',
  previewAudience: '대상 미리보기', previewRequired: '게시하기 전에 현재 대상을 미리 확인하세요.', previewLoading: '현재 수신자 확인 중…', audienceSnapshot: '대상 스냅샷', recipients: '명의 활성 수신자', excluded: '명의 비활성 구성원 제외', languages: '알림 언어', previewBasis: '이 미리보기는 동적입니다. 변경 불가능한 수신자 스냅샷은 업데이트가 실제로 게시될 때만 생성됩니다.', scheduledFor: '예약 게시', schedulePlaceholder: 'ISO 날짜/시간 예: 2030-08-10T10:00:00Z', publishNow: '지금 게시', in15Minutes: '15분 후', inOneHour: '1시간 후', tomorrow: '내일', scheduleInvalid: '미래의 ISO 날짜와 시간을 입력하세요.', notificationClass: '알림 등급', routine: '일반', urgent: '긴급', critical: '매우 긴급', notificationMapping: '서버는 일반 → 일반, 중요 → 긴급, 비상 → 매우 긴급으로 매핑합니다. 클라이언트는 이 매핑을 변경할 수 없습니다.', overrideCategory: '승인된 우선 전달 범주', safety: '안전', security: '보안', operations: '운영', weather: '날씨', businessContinuity: '업무 연속성', overrideReason: '방해 금지 시간 우선 전달 사유', overrideReasonPlaceholder: '비근무 시간 또는 음소거 상태에서 전달해야 하는 승인된 운영 사유', overrideAudit: '긴급 및 매우 긴급 전달에는 최근 MFA, 승인된 범주, 감사되는 사유가 필요합니다. 비상 경보나 긴급 서비스를 대신하지 않습니다.', attestation: '확인 진술 요구', attestationPrompt: '확인 진술 문구', attestationPlaceholder: '이 지침을 읽고 이해했습니다.', attestationEvidence: 'Newone은 정확한 공지 버전과 식별 가능한 세션/설치 스냅샷을 기록합니다. 열기나 스크롤을 확인으로 간주하지 않습니다.', reminders: '확인 알림 사용', deadline: '확인 기한', deadlinePlaceholder: '미래 ISO 날짜/시간', intervalMinutes: '알림 간격(분)', maximumReminders: '최대 알림 수(1~20)', escalateMinutes: '게시 후 에스컬레이션(분)', policyInvalid: '기한, 알림 간격 및 에스컬레이션 값이 표시된 범위를 충족해야 합니다.', smsDisabled: '이 빌드에서는 SMS 대체 전달이 비활성화되어 있습니다. SMS 전달을 주장하기 전에 외부 대체 수단을 구성하고 승인하세요.', publisherView: '게시자 제어 센터', publisherDescription: '예약 항목, 변경 불가능한 수정 이력, 공지 범위 응답 상태입니다. 최근 MFA가 필요합니다.', refreshPublisher: '게시자 보기 새로고침', recentMfaRequired: '게시자 응답 정보를 불러오려면 MFA로 다시 인증하세요.', noManagedUpdates: '승인된 게시자 범위에 업데이트가 없습니다.', snapshotPending: '게시 시까지 대상 스냅샷 대기', version: '버전', versions: '버전 이력', delivered: '전달됨', read: '읽음', acknowledgedCount: '확인됨', overdue: '기한 초과', unreachable: '활성 푸시 기기 없음', nonAcknowledged: '미확인', viewNonResponders: '미확인자 보기', nonResponderTitle: '이 공지의 미확인자', nonResponderPrivacy: '이 승인된 목록은 정확한 공지 버전의 응답 상태만 포함하며 관련 없는 채팅이나 활동을 공개하지 않습니다.', loadMore: '더 보기', pendingReachability: '푸시 대기', deliveredReachability: '전달됨', unreachableReachability: '활성 푸시 기기 없음', reminded: '알림 횟수', escalated: '에스컬레이션됨', cancelScheduled: '예약 업데이트 취소', cancelReason: '취소 사유', cancelReasonPlaceholder: '이 예약 게시를 보내지 않아야 하는 이유', confirmCancel: '게시 취소', correct: '수정본 게시', correctionTitle: '게시된 업데이트 수정', correctionDescription: '수정본은 새로운 변경 불가능한 버전을 만듭니다. 이전 버전과 확인 기록은 유지되며 필요한 경우 수신자는 새 버전을 다시 확인해야 합니다.', correctionReason: '수정 사유', correctionReasonPlaceholder: '변경 내용과 이유', publishCorrection: '수정 버전 게시', correctedFrom: '수정 대상', openUpdate: '업데이트 열기', detailTitle: '공식 업데이트', markReadBoundary: '이 상세 화면을 열면 읽음 상태만 기록됩니다. 이해 확인으로 처리되지 않습니다.', acknowledgeTitle: '정확한 버전 확인', acknowledgeDescription: '이 의도적인 작업은 표시된 변경 불가능한 버전에 확인을 연결합니다.', confirmAttestation: '필수 진술을 확인합니다', confirmAcknowledgement: '이 버전 확인', acknowledgementRecorded: '식별 가능한 세션 증거와 함께 확인이 기록되었습니다.', close: '닫기', serverRejected: '보안 업데이트 서비스가 작업을 거부했습니다. 재시도 전에 권한 있는 상태를 새로고침하세요.', networkError: '보안 업데이트 서비스에 연결할 수 없습니다. 완료된 것으로 간주하지 않습니다.', saved: '권한 있는 업데이트 상태를 새로고쳤습니다.',
};

const es: UpdateCopy = {
  audienceBuilder: 'Audiencia objetivo',
  audienceBuilderDescription: 'Elige un ámbito base y, si hace falta, redúcelo por función operativa, nivel de acceso, idioma preferido o turno actual.',
  companyAudience: 'Toda la empresa',
  channelAudience: 'Miembros del canal de anuncios',
  unitAudience: 'Sedes y unidades',
  sites: 'Sedes',
  departments: 'Departamentos',
  teams: 'Equipos',
  lines: 'Líneas',
  units: 'Turnos y otras unidades',
  descendantDisclosure: 'Elegir una sede o departamento incluye a quienes solo están asignados a sus departamentos, equipos, líneas y turnos descendientes.',
  unitRequired: 'Selecciona al menos una sede, departamento, equipo, línea o unidad.',
  operationalRoles: 'Funciones operativas',
  operationalRolesDescription: 'Cargos y funciones de trabajo exactos. No son niveles de acceso de la cuenta.',
  configuredRoles: 'Funciones configuradas (separadas por comas)',
  configuredRolesPlaceholder: 'forklift_operator, safety_coordinator',
  configuredRolesInvalid: 'Usa como máximo 50 valores exactos, de hasta 160 caracteres cada uno.',
  accessRoles: 'Niveles de acceso de cuenta',
  accessRolesDescription: 'Filtro de seguridad opcional separado de los cargos y funciones operativas.',
  owner: 'Propietario', admin: 'Administrador', manager: 'Gerente', member: 'Miembro',
  preferredLanguages: 'Idiomas preferidos para mensajes',
  currentShiftOnly: 'Solo en turno ahora',
  currentShiftDescription: 'Requiere un horario empresarial autoritativo. Las publicaciones programadas se reevalúan al publicarse realmente.',
  exclusionBreakdown: 'Excluidos', inactive: 'inactivos', selectorMismatch: 'fuera de los selectores',
  statusDraft: 'Borrador',
  statusScheduled: 'Programada',
  statusPublished: 'Publicada',
  statusCancelled: 'Cancelada',
  statusArchived: 'Archivada',
  acknowledgementRequired: 'Confirmación obligatoria',
  noAcknowledgementRequired: 'No requiere confirmación',
  noNonResponders: 'Todas las personas de la audiencia fijada confirmaron esta versión.',
  notRead: 'No leído',
  immutableHistory: 'Las versiones anteriores permanecen inmutables y auditables.',
  previewAudience: 'Previsualizar audiencia', previewRequired: 'Previsualiza la audiencia actual antes de publicar.', previewLoading: 'Comprobando destinatarios actuales…', audienceSnapshot: 'Instantánea de audiencia', recipients: 'destinatarios activos', excluded: 'miembros inactivos excluidos', languages: 'Idiomas de notificación', previewBasis: 'Esta previsualización es dinámica. La instantánea inmutable de destinatarios se crea solo cuando se publica la actualización.', scheduledFor: 'Publicación programada', schedulePlaceholder: 'Fecha/hora ISO, por ejemplo 2030-08-10T10:00:00Z', publishNow: 'Publicar ahora', in15Minutes: 'En 15 min', inOneHour: 'En 1 hora', tomorrow: 'Mañana', scheduleInvalid: 'Usa una fecha y hora ISO futuras.', notificationClass: 'Clase de notificación', routine: 'Rutina', urgent: 'Urgente', critical: 'Crítica', notificationMapping: 'El servidor asigna Normal → Rutina, Importante → Urgente y Emergencia → Crítica. El cliente no puede cambiarlo.', overrideCategory: 'Categoría de prioridad autorizada', safety: 'Seguridad laboral', security: 'Seguridad', operations: 'Operaciones', weather: 'Clima', businessContinuity: 'Continuidad del negocio', overrideReason: 'Motivo para omitir horas de silencio', overrideReasonPlaceholder: 'Por qué se autoriza la entrega fuera de turno o con silencio', overrideAudit: 'La entrega urgente o crítica exige MFA reciente, categoría aprobada y motivo auditado. No sustituye alarmas ni servicios de emergencia.', attestation: 'Exigir declaración', attestationPrompt: 'Texto de la declaración', attestationPlaceholder: 'He leído y comprendido estas instrucciones.', attestationEvidence: 'Newone registra la versión exacta y una instantánea atribuible de sesión/instalación. Abrir o desplazarse nunca confirma la recepción.', reminders: 'Activar recordatorios de confirmación', deadline: 'Plazo de confirmación', deadlinePlaceholder: 'Fecha/hora ISO futura', intervalMinutes: 'Intervalo de recordatorio (minutos)', maximumReminders: 'Máximo de recordatorios (1–20)', escalateMinutes: 'Escalar tras publicar (minutos)', policyInvalid: 'El plazo, intervalo y escalado deben respetar los límites mostrados.', smsDisabled: 'El SMS alternativo está desactivado en esta compilación. Configura y aprueba otra vía antes de afirmar entrega por SMS.', publisherView: 'Centro de control del publicador', publisherDescription: 'Programaciones, historial inmutable y respuesta limitada al aviso. Requiere MFA reciente.', refreshPublisher: 'Actualizar vista', recentMfaRequired: 'Verifica de nuevo con MFA para cargar detalles de respuesta.', noManagedUpdates: 'No hay actualizaciones en tu ámbito autorizado.', snapshotPending: 'Instantánea pendiente hasta publicar', version: 'Versión', versions: 'Historial de versiones', delivered: 'Entregado', read: 'Leído', acknowledgedCount: 'Confirmado', overdue: 'Vencido', unreachable: 'Sin dispositivo push activo', nonAcknowledged: 'Sin confirmar', viewNonResponders: 'Ver personas sin confirmar', nonResponderTitle: 'Sin confirmar para este aviso', nonResponderPrivacy: 'Esta lista autorizada contiene solo el estado de respuesta de esta versión. No muestra chats ni actividad no relacionados.', loadMore: 'Cargar más', pendingReachability: 'Push pendiente', deliveredReachability: 'Entregado', unreachableReachability: 'Sin dispositivo push activo', reminded: 'Recordatorios', escalated: 'Escalado', cancelScheduled: 'Cancelar actualización programada', cancelReason: 'Motivo de cancelación', cancelReasonPlaceholder: 'Por qué no debe enviarse esta publicación', confirmCancel: 'Cancelar publicación', correct: 'Publicar corrección', correctionTitle: 'Corregir actualización publicada', correctionDescription: 'La corrección crea una versión nueva e inmutable. Las versiones y confirmaciones anteriores se conservan; si se exige, deben confirmar la nueva versión.', correctionReason: 'Motivo de corrección', correctionReasonPlaceholder: 'Qué cambió y por qué', publishCorrection: 'Publicar versión corregida', correctedFrom: 'Corrige', openUpdate: 'Abrir actualización', detailTitle: 'Actualización oficial', markReadBoundary: 'Abrir este detalle registra solo lectura. No confirma comprensión.', acknowledgeTitle: 'Confirmar versión exacta', acknowledgeDescription: 'Esta acción deliberada vincula tu confirmación a la versión inmutable mostrada.', confirmAttestation: 'Confirmo la declaración requerida', confirmAcknowledgement: 'Confirmar esta versión', acknowledgementRecorded: 'Confirmación registrada con evidencia atribuible de sesión.', close: 'Cerrar', serverRejected: 'El servicio seguro rechazó la acción. Actualiza el estado autoritativo antes de reintentar.', networkError: 'Newone no pudo contactar el servicio seguro. No se asume que terminó.', saved: 'Estado autoritativo actualizado.',
};

const copy: Record<AppLocale, UpdateCopy> = { en, ko, es };

export function updateCopy(locale: AppLocale) {
  return copy[locale];
}
