import type { AppLocale } from '@/i18n/catalog';

const en = {
  eyebrow: 'SECURITY · AI EGRESS',
  title: 'Organization AI policy',
  description: 'Control whether employee message content may leave Newone for approved AI processing. Messaging remains available when AI egress is disabled.',
  enabled: 'AI egress approved',
  disabled: 'AI egress denied',
  loading: 'Load current policy',
  refresh: 'Refresh policy',
  version: 'Policy version',
  disclosureTitle: 'What this approval permits',
  disclosure: 'Only the selected tasks may send necessary employee message content through OpenRouter to the exact provider routes below. Translation can send original message text; summaries can send the selected conversation source messages; language detection can send text needed to identify its language.',
  safeguards: 'Approval is not sufficient by itself. The separate deployment kill switch must also be enabled, and requests must use the approved zero-retention route with data collection, caching, fallbacks, plugins, web search, and tools disabled.',
  enableFreshness: 'Enabling requires a server-verified sign-in from the previous five minutes. This screen does not guess freshness from token timestamps. Sign in again before enabling if needed. Revocation remains available to a current AAL2 policy manager even when that login is older.',
  originalFirst: 'Original messages remain stored and visible. Disabling AI egress stops new AI processing without disabling ordinary messaging.',
  reverify: 'Sign in again before enabling',
  enable: 'Approve AI egress',
  disable: 'Deny AI egress',
  useCases: 'Approved tasks',
  languageDetection: 'Language detection',
  translation: 'Translation',
  summary: 'Conversation summaries',
  providers: 'Exact provider routes',
  providersPlaceholder: 'google-vertex/us-south1',
  providersHelp: 'Comma separated and case sensitive. Each value must exactly match the deployed provider route.',
  reason: 'Audit reason',
  reasonPlaceholder: 'Explain this approval or revocation.',
  save: 'Save exact policy',
  saving: 'Saving policy…',
  saved: 'The versioned AI policy was saved and audited.',
  invalid: 'Select at least one task and provider route when approving egress, and enter an audit reason.',
  stale: 'The policy changed elsewhere. Refresh it before saving again.',
  mfaReady: 'AAL2 session active',
  mfaLocked: 'AAL2 session required',
};

const ko: Record<keyof typeof en, string> = {
  eyebrow: '보안 · AI 외부 전송',
  title: '조직 AI 정책',
  description: '직원 메시지 콘텐츠를 승인된 AI 처리 목적으로 Newone 외부로 전송할 수 있는지 관리합니다. AI 외부 전송을 꺼도 일반 메시지는 계속 사용할 수 있습니다.',
  enabled: 'AI 외부 전송 승인됨',
  disabled: 'AI 외부 전송 거부됨',
  loading: '현재 정책 불러오기',
  refresh: '정책 새로고침',
  version: '정책 버전',
  disclosureTitle: '이 승인이 허용하는 범위',
  disclosure: '선택한 작업만 필요한 직원 메시지 콘텐츠를 OpenRouter를 통해 아래의 정확한 제공자 경로로 보낼 수 있습니다. 번역은 원문을, 요약은 선택한 대화 원본 메시지를, 언어 감지는 언어 확인에 필요한 텍스트를 전송할 수 있습니다.',
  safeguards: '이 승인만으로는 처리되지 않습니다. 별도의 배포 중단 스위치도 켜져 있어야 하며, 데이터 수집, 캐시, 대체 경로, 플러그인, 웹 검색 및 도구가 꺼진 승인된 무보존 경로만 사용해야 합니다.',
  enableFreshness: '활성화하려면 서버가 확인한 로그인이 최근 5분 이내여야 합니다. 이 화면은 토큰 시간으로 최신 여부를 추정하지 않습니다. 필요한 경우 활성화 전에 다시 로그인하세요. 철회는 로그인 시간이 더 오래되었더라도 현재 AAL2 정책 관리자에게 계속 허용됩니다.',
  originalFirst: '원본 메시지는 저장되고 계속 표시됩니다. AI 외부 전송을 끄면 일반 메시지는 유지되고 새로운 AI 처리만 중지됩니다.',
  reverify: '활성화 전에 다시 로그인',
  enable: 'AI 외부 전송 승인',
  disable: 'AI 외부 전송 거부',
  useCases: '승인된 작업',
  languageDetection: '언어 감지',
  translation: '번역',
  summary: '대화 요약',
  providers: '정확한 제공자 경로',
  providersPlaceholder: 'google-vertex/us-south1',
  providersHelp: '쉼표로 구분하며 대소문자를 구분합니다. 각 값은 배포된 제공자 경로와 정확히 일치해야 합니다.',
  reason: '감사 사유',
  reasonPlaceholder: '승인 또는 철회 이유를 설명하세요.',
  save: '정확한 정책 저장',
  saving: '정책 저장 중…',
  saved: '버전이 지정된 AI 정책을 저장하고 감사 기록에 남겼습니다.',
  invalid: '외부 전송 승인 시 하나 이상의 작업과 제공자 경로를 선택하고 감사 사유를 입력하세요.',
  stale: '정책이 다른 곳에서 변경되었습니다. 다시 불러온 뒤 저장하세요.',
  mfaReady: 'AAL2 세션 활성',
  mfaLocked: 'AAL2 세션 필요',
};

const es: Record<keyof typeof en, string> = {
  eyebrow: 'SEGURIDAD · EGRESO DE IA',
  title: 'Política de IA de la organización',
  description: 'Controla si el contenido de mensajes de empleados puede salir de Newone para procesamiento de IA aprobado. La mensajería sigue disponible cuando el egreso de IA está desactivado.',
  enabled: 'Egreso de IA aprobado',
  disabled: 'Egreso de IA denegado',
  loading: 'Cargar política actual',
  refresh: 'Actualizar política',
  version: 'Versión de política',
  disclosureTitle: 'Qué permite esta aprobación',
  disclosure: 'Solo las tareas elegidas pueden enviar el contenido necesario de mensajes de empleados mediante OpenRouter a las rutas exactas de proveedor indicadas abajo. La traducción puede enviar el texto original; los resúmenes, los mensajes fuente seleccionados; y la detección de idioma, el texto necesario para identificarlo.',
  safeguards: 'Esta aprobación no basta por sí sola. El interruptor de despliegue independiente también debe estar activado y las solicitudes deben usar la ruta aprobada sin retención, con recopilación de datos, caché, alternativas, complementos, búsqueda web y herramientas desactivados.',
  enableFreshness: 'Para habilitar se requiere un inicio de sesión verificado por el servidor durante los cinco minutos anteriores. Esta pantalla no deduce la vigencia desde marcas de tiempo del token. Vuelve a iniciar sesión antes de habilitar si es necesario. La revocación sigue disponible para un administrador de política con AAL2 actual aunque el inicio de sesión sea anterior.',
  originalFirst: 'Los mensajes originales permanecen almacenados y visibles. Desactivar el egreso de IA detiene el procesamiento nuevo sin desactivar la mensajería normal.',
  reverify: 'Iniciar sesión otra vez antes de habilitar',
  enable: 'Aprobar egreso de IA',
  disable: 'Denegar egreso de IA',
  useCases: 'Tareas aprobadas',
  languageDetection: 'Detección de idioma',
  translation: 'Traducción',
  summary: 'Resúmenes de conversación',
  providers: 'Rutas exactas de proveedor',
  providersPlaceholder: 'google-vertex/us-south1',
  providersHelp: 'Separadas por comas y sensibles a mayúsculas. Cada valor debe coincidir exactamente con la ruta desplegada.',
  reason: 'Motivo de auditoría',
  reasonPlaceholder: 'Explica esta aprobación o revocación.',
  save: 'Guardar política exacta',
  saving: 'Guardando política…',
  saved: 'La política de IA versionada se guardó y auditó.',
  invalid: 'Al aprobar el egreso, elige al menos una tarea y ruta de proveedor e indica un motivo de auditoría.',
  stale: 'La política cambió en otro lugar. Actualízala antes de volver a guardar.',
  mfaReady: 'Sesión AAL2 activa',
  mfaLocked: 'Se requiere sesión AAL2',
};

const copies = { en, ko, es } as const;

export function aiPolicyCopy(locale: AppLocale) {
  return copies[locale];
}
