import type { AppLocale } from '@/i18n/catalog';

const en = {
  eyebrow: 'OPERATIONS · POLICY-MANAGED GROUPS',
  title: 'Dynamic groups',
  description: 'Build team membership from authoritative company units, roles, and shift windows. Every change is saved as a versioned draft, previewed, then published with the exact fresh preview.',
  aal2Ready: 'MFA verified',
  aal2Locked: 'MFA required',
  securityNote: 'The server rechecks unit.manage scope, recent MFA, selector boundaries, member limits, and policy version on every step.',
  refresh: 'Refresh policies',
  loadMore: 'Load more',
  newPolicy: 'New policy',
  policies: 'Managed groups',
  noPolicies: 'No dynamic-group policies are visible in your management scope.',
  conversation: 'Managed group',
  conversationLocked: 'A policy stays bound to its original group. Start a new policy to choose another group.',
  groupKind: 'Group',
  teamKind: 'Team',
  shiftKind: 'Shift',
  selectors: 'Organization selectors',
  selectorsNote: 'Choose any site, department, team, line, or shift from the verified workspace directory.',
  site: 'Site',
  department: 'Department',
  team: 'Team',
  line: 'Line',
  shift: 'Shift',
  noUnits: 'No organization units are available.',
  descendants: 'Include descendant units',
  descendantsNote: 'Include members in child units beneath every selected unit.',
  membershipRoles: 'Account roles',
  ownerRole: 'Owner',
  adminRole: 'Admin',
  managerRole: 'Manager',
  memberRole: 'Member',
  operationalRoles: 'Operational role text',
  operationalRolesPlaceholder: 'supervisor, quality lead',
  operationalRolesNote: 'Optional, comma separated. Matching is normalized to lowercase.',
  shiftWindow: 'Shift window',
  shiftNone: 'No shift filter',
  shiftCurrent: 'Current shift',
  shiftScheduled: 'Scheduled window',
  shiftStarts: 'Scheduled start (ISO 8601)',
  shiftEnds: 'Scheduled end (ISO 8601)',
  maxMembers: 'Maximum members',
  savePreview: 'Save draft & preview',
  savingPreview: 'Saving and previewing…',
  version: 'Version',
  draft: 'Draft',
  previewed: 'Previewed',
  published: 'Published',
  active: 'Active',
  paused: 'Paused',
  previewTitle: 'Fresh membership preview',
  previewExpires: 'Publish before',
  eligible: 'Eligible',
  added: 'Add',
  removed: 'Remove',
  unchanged: 'Unchanged',
  sample: 'Sample members',
  noSample: 'No sampled members',
  publish: 'Publish exact preview',
  publishing: 'Publishing…',
  stalePreview: 'This preview is stale or the selector changed. Save and preview again.',
  pauseReason: 'Pause reason',
  pauseReasonPlaceholder: 'Explain why automated membership must stop.',
  pause: 'Pause policy',
  pausing: 'Pausing…',
  savedNotice: 'Draft saved and previewed. Review the exact changes before publishing.',
  publishedNotice: 'The preview was published. Automated membership is active.',
  pausedNotice: 'Automated membership was paused and the reason was audited.',
  invalidForm: 'Choose a group and at least one account role, then review the member limit and scheduled window.',
  accessDenied: 'You need unit management permission to view or change dynamic groups.',
};

const ko: Record<keyof typeof en, string> = {
  eyebrow: '운영 · 정책 관리 그룹',
  title: '동적 그룹',
  description: '회사 단위, 역할 및 교대 시간으로 팀 멤버십을 구성합니다. 모든 변경은 버전이 지정된 초안으로 저장되고 미리보기 후 동일한 최신 미리보기로 게시됩니다.',
  aal2Ready: 'MFA 인증 완료',
  aal2Locked: 'MFA 필요',
  securityNote: '서버는 매 단계마다 unit.manage 범위, 최근 MFA, 선택 범위, 인원 제한 및 정책 버전을 다시 확인합니다.',
  refresh: '정책 새로고침',
  loadMore: '더 불러오기',
  newPolicy: '새 정책',
  policies: '관리 그룹',
  noPolicies: '관리 범위에 표시되는 동적 그룹 정책이 없습니다.',
  conversation: '관리할 그룹',
  conversationLocked: '정책은 처음 선택한 그룹에 계속 연결됩니다. 다른 그룹은 새 정책으로 만드세요.',
  groupKind: '그룹',
  teamKind: '팀',
  shiftKind: '교대',
  selectors: '조직 선택 조건',
  selectorsNote: '검증된 작업 공간 디렉터리에서 사이트, 부서, 팀, 라인 또는 교대를 선택하세요.',
  site: '사이트',
  department: '부서',
  team: '팀',
  line: '라인',
  shift: '교대',
  noUnits: '사용 가능한 조직 단위가 없습니다.',
  descendants: '하위 단위 포함',
  descendantsNote: '선택한 각 단위 아래의 하위 단위 구성원도 포함합니다.',
  membershipRoles: '계정 역할',
  ownerRole: '소유자',
  adminRole: '관리자',
  managerRole: '매니저',
  memberRole: '구성원',
  operationalRoles: '운영 역할 텍스트',
  operationalRolesPlaceholder: 'supervisor, quality lead',
  operationalRolesNote: '선택 사항이며 쉼표로 구분합니다. 일치는 소문자로 정규화됩니다.',
  shiftWindow: '교대 시간',
  shiftNone: '교대 필터 없음',
  shiftCurrent: '현재 교대',
  shiftScheduled: '예약 시간',
  shiftStarts: '예약 시작 (ISO 8601)',
  shiftEnds: '예약 종료 (ISO 8601)',
  maxMembers: '최대 인원',
  savePreview: '초안 저장 및 미리보기',
  savingPreview: '저장하고 미리보는 중…',
  version: '버전',
  draft: '초안',
  previewed: '미리봄',
  published: '게시됨',
  active: '활성',
  paused: '일시 중지',
  previewTitle: '최신 멤버십 미리보기',
  previewExpires: '게시 기한',
  eligible: '대상',
  added: '추가',
  removed: '제거',
  unchanged: '유지',
  sample: '샘플 구성원',
  noSample: '샘플 구성원 없음',
  publish: '동일한 미리보기 게시',
  publishing: '게시 중…',
  stalePreview: '미리보기가 만료되었거나 선택 조건이 변경되었습니다. 다시 저장하고 미리보세요.',
  pauseReason: '일시 중지 사유',
  pauseReasonPlaceholder: '자동 멤버십을 중지해야 하는 이유를 설명하세요.',
  pause: '정책 일시 중지',
  pausing: '중지 중…',
  savedNotice: '초안을 저장하고 미리봤습니다. 게시 전에 정확한 변경 내용을 검토하세요.',
  publishedNotice: '미리보기를 게시했습니다. 자동 멤버십이 활성화되었습니다.',
  pausedNotice: '자동 멤버십을 일시 중지하고 사유를 감사 기록에 남겼습니다.',
  invalidForm: '그룹과 하나 이상의 계정 역할을 선택한 뒤 인원 제한 및 예약 시간을 확인하세요.',
  accessDenied: '동적 그룹을 보거나 변경하려면 단위 관리 권한이 필요합니다.',
};

const es: Record<keyof typeof en, string> = {
  eyebrow: 'OPERACIONES · GRUPOS GESTIONADOS POR POLÍTICA',
  title: 'Grupos dinámicos',
  description: 'Crea membresía de equipo desde unidades, roles y turnos oficiales. Cada cambio se guarda como borrador versionado, se previsualiza y se publica con esa vista previa exacta y vigente.',
  aal2Ready: 'MFA verificado',
  aal2Locked: 'Se requiere MFA',
  securityNote: 'El servidor vuelve a comprobar el alcance unit.manage, MFA reciente, límites del selector, máximo de miembros y versión de la política en cada paso.',
  refresh: 'Actualizar políticas',
  loadMore: 'Cargar más',
  newPolicy: 'Nueva política',
  policies: 'Grupos gestionados',
  noPolicies: 'No hay políticas de grupos dinámicos visibles en tu alcance de gestión.',
  conversation: 'Grupo gestionado',
  conversationLocked: 'La política permanece vinculada a su grupo original. Crea otra política para elegir un grupo diferente.',
  groupKind: 'Grupo',
  teamKind: 'Equipo',
  shiftKind: 'Turno',
  selectors: 'Selectores de organización',
  selectorsNote: 'Elige sitios, departamentos, equipos, líneas o turnos del directorio verificado.',
  site: 'Sede',
  department: 'Departamento',
  team: 'Equipo',
  line: 'Línea',
  shift: 'Turno',
  noUnits: 'No hay unidades de organización disponibles.',
  descendants: 'Incluir unidades descendientes',
  descendantsNote: 'Incluye miembros de unidades hijas debajo de cada unidad elegida.',
  membershipRoles: 'Roles de cuenta',
  ownerRole: 'Propietario',
  adminRole: 'Admin',
  managerRole: 'Gerente',
  memberRole: 'Miembro',
  operationalRoles: 'Texto de rol operativo',
  operationalRolesPlaceholder: 'supervisor, quality lead',
  operationalRolesNote: 'Opcional, separado por comas. La coincidencia se normaliza a minúsculas.',
  shiftWindow: 'Ventana de turno',
  shiftNone: 'Sin filtro de turno',
  shiftCurrent: 'Turno actual',
  shiftScheduled: 'Ventana programada',
  shiftStarts: 'Inicio programado (ISO 8601)',
  shiftEnds: 'Fin programado (ISO 8601)',
  maxMembers: 'Máximo de miembros',
  savePreview: 'Guardar borrador y previsualizar',
  savingPreview: 'Guardando y previsualizando…',
  version: 'Versión',
  draft: 'Borrador',
  previewed: 'Previsualizado',
  published: 'Publicado',
  active: 'Activo',
  paused: 'Pausado',
  previewTitle: 'Vista previa vigente de membresía',
  previewExpires: 'Publicar antes de',
  eligible: 'Elegibles',
  added: 'Agregar',
  removed: 'Quitar',
  unchanged: 'Sin cambio',
  sample: 'Miembros de muestra',
  noSample: 'Sin miembros de muestra',
  publish: 'Publicar vista previa exacta',
  publishing: 'Publicando…',
  stalePreview: 'La vista previa venció o cambió el selector. Guarda y previsualiza de nuevo.',
  pauseReason: 'Motivo de pausa',
  pauseReasonPlaceholder: 'Explica por qué debe detenerse la membresía automática.',
  pause: 'Pausar política',
  pausing: 'Pausando…',
  savedNotice: 'El borrador se guardó y previsualizó. Revisa los cambios exactos antes de publicar.',
  publishedNotice: 'Se publicó la vista previa. La membresía automática está activa.',
  pausedNotice: 'La membresía automática se pausó y el motivo quedó auditado.',
  invalidForm: 'Elige un grupo y al menos un rol de cuenta; revisa el límite y la ventana programada.',
  accessDenied: 'Necesitas permiso de gestión de unidades para ver o cambiar grupos dinámicos.',
};

const copies = { en, ko, es } as const;

export function dynamicGroupCopy(locale: AppLocale) {
  return copies[locale];
}
