import type { AppLocale } from '@/i18n/catalog';

const en = {
  eyebrow: 'SECURITY · ACCOUNT RECOVERY',
  title: 'Lost authenticator recovery',
  description: 'A controlled help-desk workflow for a verified TOTP authenticator that is no longer available.',
  createSelf: 'Request recovery for me',
  refresh: 'Refresh cases',
  refreshing: 'Refreshing cases',
  verifyNow: 'Verify with MFA',
  aal2Ready: 'AAL2 detected',
  aal2Locked: 'Manager actions locked',
  freshnessReady: 'The server still requires this MFA verification to be no more than five minutes old for every manager action.',
  freshnessLocked: 'Verify with MFA, then return here. The server checks AAL2 and a five-minute recent-auth window on every manager action.',
  externalBoundary: 'Newone does not perform identity verification. Follow your organization’s approved external procedure before recording verification.',
  sensitiveWarning: 'Never enter identity documents, one-time codes, authenticator secrets, government IDs, or payment data. Use only a bounded approved ticket or provider reference.',
  immutableNote: 'Statuses come from the server. It records each transition in an immutable event log; raw event contents and sensitive evidence are intentionally not returned here.',
  loading: 'Loading recovery cases…',
  empty: 'No recovery cases are visible for this organization.',
  queryLocked: 'Organization cases are available only after MFA verification. A person who lost their authenticator can still submit their own request below.',
  caseReference: 'Case reference',
  requestedFor: 'Requested for',
  reason: 'Request reason',
  created: 'Created',
  expires: 'Expires',
  completed: 'Completed',
  approvals: 'Approvals',
  verification: 'External verification',
  verificationPending: 'Not yet recorded',
  privileged: 'Privileged target · two approvals required',
  standard: 'Standard target · one approval required',
  expiredLocally: 'Expiry reached; refresh for authoritative status',
  selfSeparation: 'You are the target. The server prohibits you from verifying, approving, rejecting, or executing this case.',
  separation: 'The server enforces separate target, verifier, and approver identities. Privileged targets require two distinct approvers.',
  verify: 'Record verification',
  approve: 'Approve',
  reject: 'Reject',
  execute: 'Execute reset',
  createTitle: 'Request lost-authenticator recovery',
  createDescription: 'This creates a case only for your signed-in account and the selected verified TOTP authenticator.',
  selfServiceDescription: 'Create an expiring, self-owned case for a verified authenticator you can no longer use. Help-desk managers handle later stages separately.',
  selfServiceAal1: 'Available from an active AAL1 session; it never resets the factor immediately.',
  authenticator: 'Verified authenticator',
  authenticatorFallback: 'Verified authenticator',
  noAuthenticator: 'No verified TOTP authenticator is available for this account.',
  openSettings: 'Open security settings',
  requestReason: 'Why the authenticator is unavailable',
  requestReasonPlaceholder: 'Operational context only; do not include secrets or identity documents.',
  submitRequest: 'Create recovery case',
  verifyTitle: 'Record external verification',
  verifyDescription: 'Record only that your approved external procedure succeeded. Newone hashes the reference before storage.',
  method: 'Approved method',
  evidenceReference: 'Approved ticket or provider reference',
  evidencePlaceholder: 'Reference only, 8–500 characters',
  recordVerification: 'Record verification',
  approveTitle: 'Approve recovery case',
  approveDescription: 'Approval is independent. The server rejects the target and the person who recorded verification.',
  approveConfirm: 'Confirm independent approval',
  rejectTitle: 'Reject recovery case',
  rejectDescription: 'Rejection is terminal and is recorded in the immutable event log.',
  rejectionReason: 'Rejection reason',
  rejectionPlaceholder: 'Concise operational reason; no sensitive identifiers.',
  rejectConfirm: 'Reject case',
  executeTitle: 'Execute authenticator reset',
  executeDescription: 'This deletes the bound TOTP factor and revokes every session and registered device for the target.',
  executeWarning: 'This action is destructive and cannot be undone. The security notice is only queued for external delivery; this screen does not claim delivery.',
  executeConfirm: 'Delete factor and revoke sessions',
  cancel: 'Cancel',
  working: 'Submitting…',
  noticeCreated: 'Recovery case created. It expires {expiry} and requires {approvals} approval(s) after external verification.',
  noticeVerified: 'External verification was recorded as a hash. The raw reference is no longer held by this screen.',
  noticeApproved: 'Approval recorded: {recorded} of {required}.',
  noticeRejected: 'The recovery case was rejected.',
  noticeExecuted: 'Reset completed: the factor was deleted and all sessions were revoked ({sessions} session bindings, {devices} devices). A security notice is queued for external delivery, not confirmed delivered.',
  noticeAlreadyExecuted: 'The case was already completed. No new provider-delivery receipt was returned; the case list was refreshed.',
  errorGeneric: 'The server rejected this action. Refresh and verify with MFA again before retrying.',
  errorNetwork: 'Newone could not reach the recovery service. The same action can be retried safely while this dialog remains open.',
  errorAuth: 'Your session or recent MFA verification is no longer sufficient. Verify with MFA again.',
  errorConflict: 'The case changed or this action conflicts with server policy. Refresh before continuing.',
  errorInput: 'Check the bounded reason or reference and try again.',
  errorResponse: 'The recovery service returned an invalid response. Nothing is treated as completed.',
  methodInPerson: 'In person',
  methodManagerCallback: 'Manager callback',
  methodHrRecord: 'HR record match',
  methodProvider: 'Approved provider',
  statusAwaitingVerification: 'Awaiting external verification',
  statusAwaitingApproval: 'Awaiting approval',
  statusApproved: 'Approved',
  statusExecuting: 'Executing',
  statusCompleted: 'Completed',
  statusRejected: 'Rejected',
  statusExpired: 'Expired',
} as const;

type RecoveryCopy = { [Key in keyof typeof en]: string };

const ko: RecoveryCopy = {
  eyebrow: '보안 · 계정 복구',
  title: '분실한 인증 앱 복구',
  description: '더 이상 사용할 수 없는 검증된 TOTP 인증 앱을 위한 통제된 헬프데스크 절차입니다.',
  createSelf: '내 복구 요청 만들기',
  refresh: '사례 새로고침',
  refreshing: '사례 새로고침 중',
  verifyNow: 'MFA로 인증',
  aal2Ready: 'AAL2 확인됨',
  aal2Locked: '관리 작업 잠김',
  freshnessReady: '서버는 모든 관리 작업에서 MFA 인증이 5분 이내인지 다시 확인합니다.',
  freshnessLocked: 'MFA로 인증한 뒤 돌아오세요. 서버는 모든 관리 작업에서 AAL2와 5분 이내의 최근 인증을 확인합니다.',
  externalBoundary: 'Newone은 신원 확인을 수행하지 않습니다. 확인을 기록하기 전에 조직에서 승인한 외부 절차를 따르세요.',
  sensitiveWarning: '신분증 문서, 일회용 코드, 인증 앱 비밀키, 정부 발급 ID 또는 결제 정보를 입력하지 마세요. 제한된 승인 티켓 또는 제공업체 참조만 사용하세요.',
  immutableNote: '상태는 서버에서 제공됩니다. 서버는 각 전환을 변경 불가능한 이벤트 로그에 기록하며 원시 이벤트 내용과 민감한 증거는 이 화면에 반환하지 않습니다.',
  loading: '복구 사례 불러오는 중…',
  empty: '이 조직에서 볼 수 있는 복구 사례가 없습니다.',
  queryLocked: '조직 사례는 MFA 인증 후에만 볼 수 있습니다. 인증 앱을 분실한 사용자는 아래에서 본인의 요청을 제출할 수 있습니다.',
  caseReference: '사례 참조',
  requestedFor: '대상 사용자',
  reason: '요청 사유',
  created: '생성',
  expires: '만료',
  completed: '완료',
  approvals: '승인',
  verification: '외부 확인',
  verificationPending: '아직 기록되지 않음',
  privileged: '권한 보유 대상 · 승인 2건 필요',
  standard: '일반 대상 · 승인 1건 필요',
  expiredLocally: '만료 시간이 지났습니다. 서버 상태를 새로고침하세요',
  selfSeparation: '본인이 대상입니다. 서버는 본인이 이 사례를 확인, 승인, 거부 또는 실행하지 못하도록 차단합니다.',
  separation: '서버는 대상자, 확인자, 승인자를 분리합니다. 권한 보유 대상은 서로 다른 승인자 2명이 필요합니다.',
  verify: '확인 기록',
  approve: '승인',
  reject: '거부',
  execute: '재설정 실행',
  createTitle: '분실한 인증 앱 복구 요청',
  createDescription: '로그인한 본인 계정과 선택한 검증된 TOTP 인증 앱에 대해서만 사례를 만듭니다.',
  selfServiceDescription: '더 이상 사용할 수 없는 검증된 인증 앱에 대해 만료되는 본인 소유 사례를 만드세요. 이후 단계는 헬프데스크 관리자가 별도로 처리합니다.',
  selfServiceAal1: '활성 AAL1 세션에서 사용할 수 있으며 인증 요소를 즉시 재설정하지 않습니다.',
  authenticator: '검증된 인증 앱',
  authenticatorFallback: '검증된 인증 앱',
  noAuthenticator: '이 계정에서 사용할 수 있는 검증된 TOTP 인증 앱이 없습니다.',
  openSettings: '보안 설정 열기',
  requestReason: '인증 앱을 사용할 수 없는 이유',
  requestReasonPlaceholder: '운영 맥락만 입력하세요. 비밀정보나 신분증 문서는 포함하지 마세요.',
  submitRequest: '복구 사례 만들기',
  verifyTitle: '외부 확인 기록',
  verifyDescription: '승인된 외부 절차가 성공했다는 사실만 기록하세요. Newone은 저장 전에 참조를 해시 처리합니다.',
  method: '승인된 방법',
  evidenceReference: '승인된 티켓 또는 제공업체 참조',
  evidencePlaceholder: '참조만 입력, 8~500자',
  recordVerification: '확인 기록',
  approveTitle: '복구 사례 승인',
  approveDescription: '승인은 독립적으로 수행됩니다. 서버는 대상자와 확인 기록자를 거부합니다.',
  approveConfirm: '독립 승인 확인',
  rejectTitle: '복구 사례 거부',
  rejectDescription: '거부는 최종 상태이며 변경 불가능한 이벤트 로그에 기록됩니다.',
  rejectionReason: '거부 사유',
  rejectionPlaceholder: '간결한 운영 사유를 입력하세요. 민감한 식별자는 제외하세요.',
  rejectConfirm: '사례 거부',
  executeTitle: '인증 앱 재설정 실행',
  executeDescription: '연결된 TOTP 요소를 삭제하고 대상자의 모든 세션과 등록 기기를 해지합니다.',
  executeWarning: '이 작업은 되돌릴 수 없습니다. 보안 알림은 외부 전송 대기열에 추가될 뿐이며 이 화면은 전달 완료를 주장하지 않습니다.',
  executeConfirm: '요소 삭제 및 세션 해지',
  cancel: '취소',
  working: '제출 중…',
  noticeCreated: '복구 사례가 생성되었습니다. {expiry}에 만료되며 외부 확인 후 승인 {approvals}건이 필요합니다.',
  noticeVerified: '외부 확인이 해시로 기록되었습니다. 이 화면은 원시 참조를 더 이상 보관하지 않습니다.',
  noticeApproved: '승인이 기록되었습니다: {recorded}/{required}.',
  noticeRejected: '복구 사례가 거부되었습니다.',
  noticeExecuted: '재설정 완료: 요소가 삭제되고 모든 세션이 해지되었습니다(세션 연결 {sessions}개, 기기 {devices}개). 보안 알림은 외부 전송 대기 중이며 전달 완료가 아닙니다.',
  noticeAlreadyExecuted: '사례가 이미 완료되었습니다. 새 제공업체 전달 영수증은 반환되지 않았으며 사례 목록을 새로고쳤습니다.',
  errorGeneric: '서버가 작업을 거부했습니다. 새로고침하고 MFA로 다시 인증한 후 재시도하세요.',
  errorNetwork: '복구 서비스에 연결할 수 없습니다. 이 대화상자가 열린 동안 같은 작업을 안전하게 재시도할 수 있습니다.',
  errorAuth: '세션 또는 최근 MFA 인증이 충분하지 않습니다. MFA로 다시 인증하세요.',
  errorConflict: '사례가 변경되었거나 작업이 서버 정책과 충돌합니다. 계속하기 전에 새로고침하세요.',
  errorInput: '제한된 사유 또는 참조를 확인하고 다시 시도하세요.',
  errorResponse: '복구 서비스가 잘못된 응답을 반환했습니다. 어떤 작업도 완료된 것으로 처리하지 않습니다.',
  methodInPerson: '대면 확인',
  methodManagerCallback: '관리자 회신 통화',
  methodHrRecord: 'HR 기록 대조',
  methodProvider: '승인된 제공업체',
  statusAwaitingVerification: '외부 확인 대기',
  statusAwaitingApproval: '승인 대기',
  statusApproved: '승인됨',
  statusExecuting: '실행 중',
  statusCompleted: '완료됨',
  statusRejected: '거부됨',
  statusExpired: '만료됨',
};

const es: RecoveryCopy = {
  eyebrow: 'SEGURIDAD · RECUPERACIÓN DE CUENTA',
  title: 'Recuperación de autenticador perdido',
  description: 'Un proceso controlado de soporte para un autenticador TOTP verificado que ya no está disponible.',
  createSelf: 'Solicitar mi recuperación',
  refresh: 'Actualizar casos',
  refreshing: 'Actualizando casos',
  verifyNow: 'Verificar con MFA',
  aal2Ready: 'AAL2 detectado',
  aal2Locked: 'Acciones administrativas bloqueadas',
  freshnessReady: 'El servidor exige que la verificación MFA tenga menos de cinco minutos para cada acción administrativa.',
  freshnessLocked: 'Verifica con MFA y vuelve aquí. El servidor comprueba AAL2 y una autenticación de menos de cinco minutos en cada acción administrativa.',
  externalBoundary: 'Newone no verifica identidades. Sigue el procedimiento externo aprobado por tu organización antes de registrar la verificación.',
  sensitiveWarning: 'Nunca ingreses documentos de identidad, códigos de un solo uso, secretos del autenticador, identificaciones oficiales ni datos de pago. Usa solo una referencia limitada de ticket o proveedor aprobada.',
  immutableNote: 'Los estados provienen del servidor. Cada transición se registra en un historial inmutable; el contenido bruto de eventos y la evidencia sensible no se devuelven aquí.',
  loading: 'Cargando casos de recuperación…',
  empty: 'No hay casos de recuperación visibles para esta organización.',
  queryLocked: 'Los casos de la organización solo están disponibles después de MFA. Una persona que perdió su autenticador aún puede enviar su propia solicitud abajo.',
  caseReference: 'Referencia del caso',
  requestedFor: 'Solicitado para',
  reason: 'Motivo de la solicitud',
  created: 'Creado',
  expires: 'Vence',
  completed: 'Completado',
  approvals: 'Aprobaciones',
  verification: 'Verificación externa',
  verificationPending: 'Aún no registrada',
  privileged: 'Objetivo privilegiado · requiere dos aprobaciones',
  standard: 'Objetivo estándar · requiere una aprobación',
  expiredLocally: 'Se alcanzó el vencimiento; actualiza para obtener el estado autoritativo',
  selfSeparation: 'Tú eres el objetivo. El servidor impide que verifiques, apruebes, rechaces o ejecutes este caso.',
  separation: 'El servidor separa las identidades del objetivo, verificador y aprobador. Los objetivos privilegiados requieren dos aprobadores distintos.',
  verify: 'Registrar verificación',
  approve: 'Aprobar',
  reject: 'Rechazar',
  execute: 'Ejecutar restablecimiento',
  createTitle: 'Solicitar recuperación del autenticador',
  createDescription: 'Esto crea un caso solo para tu cuenta activa y el autenticador TOTP verificado seleccionado.',
  selfServiceDescription: 'Crea un caso temporal y propio para un autenticador verificado que ya no puedes usar. El soporte gestiona las etapas posteriores por separado.',
  selfServiceAal1: 'Disponible desde una sesión AAL1 activa; nunca restablece el factor de inmediato.',
  authenticator: 'Autenticador verificado',
  authenticatorFallback: 'Autenticador verificado',
  noAuthenticator: 'No hay un autenticador TOTP verificado disponible para esta cuenta.',
  openSettings: 'Abrir configuración de seguridad',
  requestReason: 'Por qué el autenticador no está disponible',
  requestReasonPlaceholder: 'Solo contexto operativo; no incluyas secretos ni documentos de identidad.',
  submitRequest: 'Crear caso de recuperación',
  verifyTitle: 'Registrar verificación externa',
  verifyDescription: 'Registra únicamente que el procedimiento externo aprobado tuvo éxito. Newone cifra la referencia con hash antes de almacenarla.',
  method: 'Método aprobado',
  evidenceReference: 'Referencia aprobada de ticket o proveedor',
  evidencePlaceholder: 'Solo referencia, 8–500 caracteres',
  recordVerification: 'Registrar verificación',
  approveTitle: 'Aprobar caso de recuperación',
  approveDescription: 'La aprobación es independiente. El servidor rechaza al objetivo y a quien registró la verificación.',
  approveConfirm: 'Confirmar aprobación independiente',
  rejectTitle: 'Rechazar caso de recuperación',
  rejectDescription: 'El rechazo es definitivo y se registra en el historial inmutable.',
  rejectionReason: 'Motivo del rechazo',
  rejectionPlaceholder: 'Motivo operativo conciso, sin identificadores sensibles.',
  rejectConfirm: 'Rechazar caso',
  executeTitle: 'Ejecutar restablecimiento del autenticador',
  executeDescription: 'Esto elimina el factor TOTP vinculado y revoca todas las sesiones y dispositivos registrados del objetivo.',
  executeWarning: 'Esta acción es destructiva e irreversible. El aviso de seguridad solo queda en cola para entrega externa; esta pantalla no afirma que fue entregado.',
  executeConfirm: 'Eliminar factor y revocar sesiones',
  cancel: 'Cancelar',
  working: 'Enviando…',
  noticeCreated: 'Caso creado. Vence {expiry} y requiere {approvals} aprobación(es) después de la verificación externa.',
  noticeVerified: 'La verificación externa se registró como hash. Esta pantalla ya no conserva la referencia original.',
  noticeApproved: 'Aprobación registrada: {recorded} de {required}.',
  noticeRejected: 'El caso de recuperación fue rechazado.',
  noticeExecuted: 'Restablecimiento completado: se eliminó el factor y se revocaron todas las sesiones ({sessions} vínculos, {devices} dispositivos). El aviso está en cola para entrega externa, no confirmado como entregado.',
  noticeAlreadyExecuted: 'El caso ya estaba completado. No se devolvió un nuevo recibo de entrega del proveedor; se actualizó la lista.',
  errorGeneric: 'El servidor rechazó la acción. Actualiza y verifica con MFA otra vez antes de reintentar.',
  errorNetwork: 'Newone no pudo contactar el servicio. Puedes reintentar la misma acción de forma segura mientras este diálogo siga abierto.',
  errorAuth: 'Tu sesión o verificación MFA reciente ya no es suficiente. Verifica con MFA de nuevo.',
  errorConflict: 'El caso cambió o la acción entra en conflicto con la política del servidor. Actualiza antes de continuar.',
  errorInput: 'Revisa el motivo o referencia limitados e inténtalo otra vez.',
  errorResponse: 'El servicio devolvió una respuesta inválida. Nada se considera completado.',
  methodInPerson: 'En persona',
  methodManagerCallback: 'Llamada del gerente',
  methodHrRecord: 'Coincidencia con registro de RR. HH.',
  methodProvider: 'Proveedor aprobado',
  statusAwaitingVerification: 'Esperando verificación externa',
  statusAwaitingApproval: 'Esperando aprobación',
  statusApproved: 'Aprobado',
  statusExecuting: 'Ejecutando',
  statusCompleted: 'Completado',
  statusRejected: 'Rechazado',
  statusExpired: 'Vencido',
};

const copies: Record<AppLocale, RecoveryCopy> = { en, ko, es };

export function recoveryCopy(locale: AppLocale): RecoveryCopy {
  return copies[locale] ?? en;
}

export function interpolateRecoveryCopy(
  template: string,
  values: Record<string, string | number>,
) {
  return template.replace(/\{([a-z]+)\}/g, (match, key: string) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}
